version: '3.7'

services:
  master:
    platform: linux/x86_64
    container_name: mysql_master
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./config/master:/conf
      - master_db:/var/lib/mysql
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_HOME: /conf
  slave:
    platform: linux/x86_64
    container_name: mysql_slave
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./config/slave:/conf
      - slave_db:/var/lib/mysql
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_HOME: /conf
  restore:
    platform: linux/x86_64
    container_name: mysql_restore
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./config/restore:/conf
      - restore_db:/var/lib/mysql
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_HOME: /conf
  ruby:
    working_dir: /ruby
    image: ruby:3.1.4-buster
    container_name: ruby
    volumes:
      - ./ruby/:/ruby

volumes:
  master_db:
  slave_db:
  restore_db:
