version: '3'

tasks:
  up:
    cmds:
      - docker compose up -d
    silent: true
  
  down:
    cmds:
      - docker compose down
    silent: true
  
  run:
    cmds:
      - docker compose run --rm {{ .CLI_ARGS }}
    silent: true
  
  exec:
    cmds:
      - docker compose exec {{ .CLI_ARGS }}
    silent: true
